'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)
export default function StorePage({ params }){
  const [store,setStore]=useState(null);const[products,setProducts]=useState([]);const[cart,setCart]=useState([]);const[showCart,setShowCart]=useState(false);const[previewProduct,setPreviewProduct]=useState(null);const slug=params.slug
  useEffect(()=>{async function load(){const{data:s}=await supabase.from('stores').select('*').eq('slug',slug).single();if(s){setStore(s);const{data:prods}=await supabase.from('products').select('*').eq('store_id',s.id).eq('is_active',true).order('created_at',{ascending:false});setProducts(prods||[])}}load()},[slug])
  const addToCart=(p)=>{const ex=cart.find(c=>c.id===p.id);if(ex)setCart(cart.map(c=>c.id===p.id?{...c,qty:c.qty+1}:c));else setCart([...cart,{...p,qty:1}]);setShowCart(true)}
  const removeFromCart=(id)=>setCart(cart.filter(c=>c.id!==id));const updateQty=(id,q)=>{if(q<=0)removeFromCart(id);else setCart(cart.map(c=>c.id===id?{...c,qty:q}:c))}
  const total=cart.reduce((s,c)=>s+parseFloat(c.price)*c.qty,0);const totalItems=cart.reduce((s,c)=>s+c.qty,0)
  const checkout=()=>{let msg=`Hola ${store.name}! Quiero:%0A`;cart.forEach(c=>{msg+=`- ${c.name} x${c.qty} = C$ ${c.price*c.qty}%0A`});msg+=`Total: C$ ${total}`;window.open(`https://wa.me/${store.whatsapp}?text=${msg}`,'_blank')}
  if(!store)return<div className='p-10'>Cargando...</div>
  return(<main className='min-h-screen bg-white'>
  <div className='sticky top-0 z-30 bg-white border-b'><div className='max-w-5xl mx-auto px-6 py-3 flex justify-between items-center'><p className='font-black'>{store.name}</p><button onClick={()=>setShowCart(true)} className='bg-black text-white rounded-full px-5 py-2 font-bold text-sm'>🛒 Carrito {totalItems>0&&<span className='bg-green-500 text-black ml-2 px-2 py-0.5 rounded-full text-xs'>{totalItems}</span>}</button></div></div>
  <div className='w-full h-[300px] bg-black relative overflow-hidden'>{store.cover_image?<img src={store.cover_image} className='w-full h-full object-cover'/>:<div className='w-full h-full bg-green-500'/>}<div className='absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex items-end p-6'><h1 className='text-white font-black text-4xl'>{store.name}</h1></div></div>
  <div className='bg-black text-white px-6 py-3'><div className='max-w-5xl mx-auto flex gap-2 flex-wrap'><div className='bg-green-500 text-black rounded-full px-4 py-1 text-[11px] font-black'>KIT BANNER: Envio rapido Paiwas - Paga al recibir</div><div className='bg-white/10 rounded-full px-4 py-1 text-[11px]'>Abierto hoy 8am-9pm</div><div className='bg-white/10 rounded-full px-4 py-1 text-[11px]'>Entrega 30 min</div></div></div>
  <div className='max-w-5xl mx-auto p-6'><div className='grid grid-cols-1 md:grid-cols-3 gap-5'>{products.map(p=>(<div key={p.id} className='border rounded-2xl overflow-hidden'><div className='h-[180px] bg-gray-100 cursor-pointer' onClick={()=>setPreviewProduct(p)}><img src={p.image_url} className='w-full h-full object-cover'/></div><div className='p-3'><p className='font-bold'>{p.name}</p><p className='text-sm'>C$ {p.price}</p><div className='flex gap-2 mt-2'><button onClick={()=>addToCart(p)} className='flex-1 border border-black rounded-full py-2 text-sm font-bold'>+ Carrito</button><button onClick={()=>{const m=`Hola ${store.name}! Quiero ${p.name}`;window.open(`https://wa.me/${store.whatsapp}?text=${m}`,'_blank')}} className='flex-1 bg-black text-white rounded-full py-2 text-sm'>Pedir</button></div></div></div>))}</div></div>
  {previewProduct&&(<div className='fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4' onClick={()=>setPreviewProduct(null)}><div className='bg-white rounded-[24px] max-w-md w-full overflow-hidden' onClick={e=>e.stopPropagation()}><div className='h-[350px] bg-white flex items-center justify-center p-2'><img src={previewProduct.image_url} className='w-full h-full object-contain'/></div><div className='p-5'><h3 className='font-black text-xl'>{previewProduct.name}</h3><p>C$ {previewProduct.price}</p><div className='flex gap-2 mt-4'><button onClick={()=>{addToCart(previewProduct);setPreviewProduct(null)}} className='flex-1 border-2 border-black rounded-full py-3 font-bold'>+ Carrito</button><button onClick={()=>{const m=`Hola ${store.name}! Quiero ${previewProduct.name}`;window.open(`https://wa.me/${store.whatsapp}?text=${m}`,'_blank')}} className='flex-1 bg-black text-white rounded-full py-3 font-bold'>WhatsApp</button></div></div></div></div>)}
  {showCart&&(<div className='fixed inset-0 bg-black/60 z-50 flex justify-end'><div className='bg-white w-full max-w-md h-full flex flex-col'><div className='p-5 bg-black text-white flex justify-between'><h3 className='font-black'>Tu carrito ({totalItems})</h3><button onClick={()=>setShowCart(false)} className='bg-white text-black rounded-full px-3 py-1'>X</button></div><div className='flex-1 overflow-auto p-5 space-y-3'>{cart.length===0?<p className='text-center text-gray-400 mt-20'>Vacio - agrega con + Carrito</p>:cart.map(c=>(<div key={c.id} className='flex gap-3 border rounded-xl p-3'><img src={c.image_url} className='w-14 h-14 object-cover rounded-lg'/><div className='flex-1'><p className='font-bold text-sm'>{c.name}</p><p className='text-xs'>C$ {c.price} x {c.qty}</p><div className='flex gap-2 mt-1'><button onClick={()=>updateQty(c.id,c.qty-1)} className='w-6 h-6 border rounded-full'>-</button><span>{c.qty}</span><button onClick={()=>updateQty(c.id,c.qty+1)} className='w-6 h-6 border rounded-full'>+</button></div></div><button onClick={()=>removeFromCart(c.id)} className='text-xs text-red-500 border px-2 py-1 rounded-full'>Quitar</button></div>))}</div><div className='p-5 border-t'><div className='flex justify-between font-black text-lg'><span>Total</span><span>C$ {total}</span></div><button onClick={checkout} disabled={cart.length===0} className='w-full mt-4 bg-green-500 text-black font-black py-4 rounded-full disabled:opacity-30'>Enviar por WhatsApp</button></div></div></div>)}
  {cart.length>0&&!showCart&&(<div className='fixed bottom-0 left-0 right-0 bg-white border-t p-4'><div className='max-w-5xl mx-auto flex justify-between items-center'><span className='font-bold'>{totalItems} prod - C$ {total}</span><button onClick={()=>setShowCart(true)} className='bg-black text-white px-6 py-3 rounded-full'>Ver carrito</button></div></div>)}
  </main>)
}
