'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)
export default function OwnerAdmin({ params }){
  const slug=params.slug;const[store,setStore]=useState(null);const[isAuth,setIsAuth]=useState(false);const[passInput,setPassInput]=useState('');const[products,setProducts]=useState([]);const[form,setForm]=useState({name:'',price:'',image_url:''});const[coverFile,setCoverFile]=useState(null);const[coverPreview,setCoverPreview]=useState(null);const[prodPreview,setProdPreview]=useState(null);const[log,setLog]=useState('')
  useEffect(()=>{async function load(){const{data}=await supabase.from('stores').select('*').eq('slug',slug).single();if(data){setStore(data);const{data:prods}=await supabase.from('products').select('*').eq('store_id',data.id).order('created_at',{ascending:false});setProducts(prods||[]);const saved=localStorage.getItem('tn_owner_'+data.slug);if(saved&&saved===data.whatsapp)setIsAuth(true)}}load()},[])
  const handleLogin=(e)=>{e.preventDefault();if(passInput===store.whatsapp||passInput===store.owner_password){localStorage.setItem('tn_owner_'+store.slug,store.whatsapp);setIsAuth(true)}else alert('Usa tu WhatsApp: '+store.whatsapp)}
  const uploadImage=async(file)=>{const fileName=Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9.]/g,'-');const{error}=await supabase.storage.from('tienda-images').upload(fileName,file);if(error){alert(error.message);return null}const{data}=supabase.storage.from('tienda-images').getPublicUrl(fileName);return data.publicUrl}
  const handleCoverChange=(e)=>{const f=e.target.files[0];if(f){setCoverFile(f);setCoverPreview(URL.createObjectURL(f))}}
  const handleProdChange=(e)=>{const f=e.target.files[0];if(f)setProdPreview(URL.createObjectURL(f))}
  const updateCover=async()=>{setLog('Subiendo...');const url=await uploadImage(coverFile);if(url){await supabase.from('stores').update({cover_image:url}).eq('id',store.id);setStore({...store,cover_image:url});setLog('Actualizada');setCoverFile(null);setCoverPreview(null)}}
  const createProduct=async(e)=>{e.preventDefault();let imageUrl=form.image_url;const inp=document.getElementById('prod-file');if(inp&&inp.files[0]){const up=await uploadImage(inp.files[0]);if(up)imageUrl=up}await supabase.from('products').insert({store_id:store.id,name:form.name,price:parseFloat(form.price),image_url:imageUrl,is_active:true});setForm({name:'',price:'',image_url:''});setProdPreview(null);const{data}=await supabase.from('products').select('*').eq('store_id',store.id).order('created_at',{ascending:false});setProducts(data||[])}
  if(!store)return<div> Cargando </div>
  if(!isAuth)return(<main className='min-h-screen bg-black flex items-center justify-center p-6'><div className='bg-white rounded-[24px] p-8 max-w-sm w-full text-center'><h1 className='font-black'>Admin {store.name}</h1><form onSubmit={handleLogin} className='mt-6 space-y-3'><input type='password' className='w-full border rounded-xl px-4 py-3 text-center' placeholder={store.whatsapp} value={passInput} onChange={e=>setPassInput(e.target.value)} required/><button className='w-full bg-black text-white py-3 rounded-full font-bold'>Entrar</button><p className='text-[10px] text-gray-400'>Tu pass es tu WhatsApp como antes</p></form></div></main>)
  return(<main className='min-h-screen bg-[#fafaf9] p-6'><div className='max-w-5xl mx-auto'><h1 className='font-black text-xl'>Panel {store.name}</h1><div className='grid md:grid-cols-3 gap-6 mt-6'><div className='bg-white border rounded-2xl p-5'><h2 className='font-bold'>Portada</h2><div className='w-full h-36 bg-gray-100 rounded-xl mt-3 overflow-hidden'>{coverPreview?<img src={coverPreview} className='w-full h-full object-cover object-center'/>:store.cover_image?<img src={store.cover_image} className='w-full h-full object-cover object-center'/>:<div className='w-full h-full flex items-center justify-center text-xs'>Sin portada</div>}</div><input type='file' accept='image/*' className='w-full mt-3 text-sm' onChange={handleCoverChange}/><button onClick={updateCover} disabled={!coverFile} className='w-full mt-2 bg-black text-white py-2 rounded-full text-sm disabled:opacity-30'>Subir portada</button><p className='text-xs'>{log}</p><img src={`https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=https://tiendanica.store/${store.slug}`} className='w-40 h-40 mt-6 border rounded-xl'/></div><div className='md:col-span-2 space-y-6'><div className='bg-white border rounded-2xl p-5'><h2 className='font-bold'>Agregar</h2><form onSubmit={createProduct} className='mt-3 space-y-3'><input className='w-full border rounded-xl px-4 py-2' placeholder='Nombre' value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className='w-full border rounded-xl px-4 py-2' placeholder='Precio' value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/><div className='border rounded-xl p-3'><input id='prod-file' type='file' accept='image/*' className='w-full text-sm' onChange={handleProdChange}/>{prodPreview&&<div className='mt-3 h-32 bg-gray-100 rounded-xl overflow-hidden'><img src={prodPreview} className='w-full h-full object-cover object-center'/></div>}<input className='w-full border rounded-xl px-4 py-2 mt-2' placeholder='URL' value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></div><button className='w-full bg-green-500 py-3 rounded-full font-bold'>Agregar</button></form></div></div></div></div></main>)
}
