'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)
export default function SuperAdmin(){
  const [isAuth,setIsAuth]=useState(false);const[pass,setPass]=useState('');const[stores,setStores]=useState([]);const[products,setProducts]=useState([]);const[selectedStore,setSelectedStore]=useState(null);const[form,setForm]=useState({name:'',slug:'',whatsapp:'',description:''});const[prodForm,setProdForm]=useState({name:'',price:'',image_url:'',id:null});const[editing,setEditing]=useState(false);const[status,setStatus]=useState('')
  useEffect(()=>{if(localStorage.getItem('tn_super_admin')==='ok')setIsAuth(true);loadStores()},[])
  const loadStores=async()=>{const{data}=await supabase.from('stores').select('*').order('created_at',{ascending:false});setStores(data||[]);if(data&&data[0]){setSelectedStore(data[0]);loadProducts(data[0].id)}setStatus(`Super Admin OK - ${data?.length||0} tiendas`)}
  const loadProducts=async(id)=>{const{data}=await supabase.from('products').select('*').eq('store_id',id).order('created_at',{ascending:false});setProducts(data||[])}
  const handleLogin=(e)=>{e.preventDefault();if(pass==='NicaAdmin2025'){localStorage.setItem('tn_super_admin','ok');setIsAuth(true)}else alert('error')}
  const saveProduct=async(e)=>{e.preventDefault();if(editing){await supabase.from('products').update({name:prodForm.name,price:parseFloat(prodForm.price),image_url:prodForm.image_url}).eq('id',prodForm.id)}else{await supabase.from('products').insert({store_id:selectedStore.id,name:prodForm.name,price:parseFloat(prodForm.price),image_url:prodForm.image_url,is_active:true})}setProdForm({name:'',price:'',image_url:'',id:null});setEditing(false);loadProducts(selectedStore.id)}
  const startEdit=(p)=>{setProdForm({name:p.name,price:p.price,image_url:p.image_url,id:p.id});setEditing(true)}
  const deleteStore=async(id)=>{if(!confirm('Borrar?'))return;await supabase.from('products').delete().eq('store_id',id);await supabase.from('stores').delete().eq('id',id);loadStores()}
  const deleteProduct=async(id)=>{await supabase.from('products').delete().eq('id',id);loadProducts(selectedStore.id)}
  if(!isAuth)return(<main className='min-h-screen bg-black flex items-center justify-center p-6'><div className='bg-white rounded-[24px] p-8 max-w-sm w-full text-center'><h1 className='font-black'>Super Admin</h1><form onSubmit={handleLogin} className='mt-6 space-y-3'><input type='password' className='w-full border rounded-xl px-4 py-3 text-center' value={pass} onChange={e=>setPass(e.target.value)} required/><button className='w-full bg-black text-white py-3 rounded-full'>Entrar</button></form></div></main>)
  return(<main className='p-6'><div className='flex justify-between'><h1 className='font-black'>TiendaNica SUPER ADMIN</h1><span className='bg-black text-green-400 text-xs px-3 py-1 rounded-full'>{status}</span></div><div className='grid lg:grid-cols-3 gap-6 mt-6'><div className='bg-white border rounded-2xl p-5'><h2 className='font-bold'>Tiendas ({stores.length})</h2>{stores.map(s=>(<div key={s.id} className='border rounded-xl p-2 mt-2 flex justify-between'><span className='text-sm font-bold'>{s.name}</span><button onClick={()=>deleteStore(s.id)} className='bg-red-500 text-white text-[10px] px-2 py-1 rounded-full'>Eliminar</button></div>))}</div><div className='lg:col-span-2 bg-white border rounded-2xl p-5'><h2 className='font-bold'>Productos {selectedStore?.name} - {editing?'Editando':'Nuevo'}</h2><form onSubmit={saveProduct} className='mt-3 space-y-2'><input className='w-full border rounded-xl px-3 py-2' placeholder='Nombre' value={prodForm.name} onChange={e=>setProdForm({...prodForm,name:e.target.value})} required/><input className='w-full border rounded-xl px-3 py-2' placeholder='Precio' value={prodForm.price} onChange={e=>setProdForm({...prodForm,price:e.target.value})} required/><input className='w-full border rounded-xl px-3 py-2' placeholder='URL imagen' value={prodForm.image_url} onChange={e=>setProdForm({...prodForm,image_url:e.target.value})}/><div className='flex gap-2'><button className='flex-1 bg-green-500 py-2 rounded-full font-bold'>{editing?'Guardar':'Agregar'}</button>{editing&&<button type='button' onClick={()=>{setEditing(false);setProdForm({name:'',price:'',image_url:'',id:null})}} className='flex-1 border py-2 rounded-full'>Cancelar</button>}</div></form><div className='grid grid-cols-3 gap-2 mt-4'>{products.map(p=>(<div key={p.id} className='border rounded-xl overflow-hidden'><img src={p.image_url} className='h-20 w-full object-cover'/><div className='p-2'><p className='text-xs font-bold'>{p.name}</p><div className='flex gap-1 mt-1'><button onClick={()=>startEdit(p)} className='flex-1 bg-black text-white text-[9px] py-1 rounded-full'>Editar</button><button onClick={()=>deleteProduct(p.id)} className='flex-1 bg-red-500 text-white text-[9px] py-1 rounded-full'>X</button></div></div></div>))}</div></div></div></main>)
}
