'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)
export default function StorePage({ params }){
  const [store,setStore]=useState(null);const[products,setProducts]=useState([]);const[cart,setCart]=useState([]);const[loading,setLoading]=useState(true);const[showCart,setShowCart]=useState(false);const[previewProduct,setPreviewProduct]=useState(null);const slug=params.slug
  useEffect(()=>{async function load(){const{data:s}=await supabase.from('stores').select('*').eq('slug',slug).single();if(s){setStore(s);const{data:prods}=await supabase.from('products').select('*').eq('store_id',s.id).eq('is_active',true).order('created_at',{ascending:false});setProducts(prods||[])}setLoading(false)}load()},[slug])
  const addToCart=(p)=>{const ex=cart.find(c=>c.id===p.id);if(ex)setCart(cart.map(c=>c.id===p.id?{...c,qty:c.qty+1}:c));else setCart([...cart,{...p,qty:1}]);setShowCart(true)}
  const removeFromCart=(id)=>setCart(cart.filter(c=>c.id!==id))
  const updateQty=(id,qty)=>{if(qty<=0)removeFromCart(id);else setCart(cart.map(c=>c.id===id?{...c,qty}:c))}
  const total=cart.reduce((s,c)=>s+parseFloat(c.price)*c.qty,0)
  const totalItems=cart.reduce((s,c)=>s+c.qty,0)
  const checkout=()=>{let msg=`Hola ${store.name}! Quiero pedir:%0A`;cart.forEach(c=>{msg+=`- ${c.name} x${c.qty} = C$ ${c.price*c.qty}%0A`});msg+=`%0ATotal: C$ ${total}%0A`;window.open(`https://wa.me/${store.whatsapp}?text=${msg}`,'_blank')}
  const pedirSolo=(p)=>{const msg=`Hola ${store.name}! Quiero ${p.name} - C$ ${p.price}`;window.open(`https://wa.me/${store.whatsapp}?text=${msg}`,'_blank')}
  if(loading)return<div className='p-10 text-center'>Cargando...</div>
  if(!store)return<div className='p-10 text-center'>Tienda no encontrada</div>
  return(<main className='min-h-screen bg-white'>
  <div className='w-full h-[260px] md:h-[360px] bg-black relative overflow-hidden'>{store.cover_image?<img src={store.cover_image} className='w-full h-full object-cover object-center'/>:<div className='w-full h-full bg-gradient-to-br from-green-500 to-black'/>}<div className='absolute inset-0 bg-gradient-to-t from-black/80 via-black/30 to-transparent flex items-end p-6'><div className='max-w-5xl mx-auto w-full'><h1 className='text-white font-black text-3xl md:text-5xl uppercase'>{store.name}</h1><p className='text-white/90 text-sm mt-2'>{store.description}</p><a href={`https://wa.me/${store.whatsapp}`} target='_blank' className='inline-block mt-3 bg-green-500 text-black font-bold px-5 py-2 rounded-full text-sm'>WhatsApp</a></div></div></div>
  
  <div className='bg-[#f6f6f3] border-b'>
    <div className='max-w-5xl mx-auto px-6 py-3 flex flex-wrap gap-2 items-center'>
      <div className='bg-black text-white rounded-full px-4 py-2 text-[11px] flex items-center gap-2'><span className='bg-green-500 text-black font-bold px-2 py-0.5 rounded-full'>NUEVO</span>Envio rapido Paiwas - Paga al recibir</div>
      <div className='bg-white border rounded-full px-4 py-2 text-[11px]'>⏰ Abierto hoy 8am - 9pm</div>
      <div className='bg-white border rounded-full px-4 py-2 text-[11px]'>📦 Entrega en 30 min</div>
    </div>
  </div>

  <div className='max-w-5xl mx-auto p-6 bg-white'><h2 className='font-black text-xl'>Productos disponibles</h2><p className='text-xs text-gray-500'>Toca la imagen para ver completa</p><div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-5 mt-5'>{products.map(p=>(<div key={p.id} className='bg-white border rounded-2xl overflow-hidden flex flex-col shadow-sm'><div className='h-[200px] bg-gray-100 overflow-hidden cursor-pointer' onClick={()=>setPreviewProduct(p)}><img src={p.image_url} className='w-full h-full object-cover object-center hover:scale-105 transition'/></div><div className='p-3 flex-1 flex flex-col'><h3 className='font-bold'>{p.name}</h3><p className='text-sm'>C$ {p.price}</p><div className='mt-auto flex gap-2 pt-3'><button onClick={()=>addToCart(p)} className='flex-1 border border-black rounded-full py-2 text-sm font-bold'>+ Carrito</button><button onClick={()=>pedirSolo(p)} className='flex-1 bg-black text-white rounded-full py-2 text-sm font-bold'>Pedir</button></div></div></div>))}</div></div>

  {previewProduct&&(<div className='fixed inset-0 bg-black/50 backdrop-blur-sm z-[60] flex items-center justify-center p-4' onClick={()=>setPreviewProduct(null)}><div className='bg-white rounded-[24px] max-w-md w-full overflow-hidden shadow-2xl' onClick={e=>e.stopPropagation()}><div className='bg-white p-2'><div className='w-full h-[350px] bg-white rounded-2xl overflow-hidden flex items-center justify-center'><img src={previewProduct.image_url} className='w-full h-full object-contain'/></div></div><div className='p-5 bg-white'><h3 className='font-black text-xl'>{previewProduct.name}</h3><p className='text-gray-600'>C$ {previewProduct.price}</p><div className='flex gap-2 mt-4'><button onClick={()=>{addToCart(previewProduct); setPreviewProduct(null)}} className='flex-1 border-2 border-black rounded-full py-3 font-bold'>+ Carrito</button><button onClick={()=>{pedirSolo(previewProduct); setPreviewProduct(null)}} className='flex-1 bg-black text-white rounded-full py-3 font-bold'>Pedir por WhatsApp</button></div><button onClick={()=>setPreviewProduct(null)} className='w-full mt-3 text-xs text-gray-400'>Cerrar</button></div></div></div>)}

  {cart.length>0&&(<><div className='fixed bottom-0 left-0 right-0 bg-white border-t p-4 z-40 shadow-[0_-10px_30px_rgba(0,0,0,0.1)]'><div className='max-w-5xl mx-auto flex justify-between items-center'><div className='flex items-center gap-3'><div className='bg-black text-white rounded-full w-8 h-8 flex items-center justify-center text-xs font-bold'>{totalItems}</div><div><p className='font-bold text-sm'>C$ {total}</p><p className='text-[10px] text-gray-500'>{totalItems} productos</p></div></div><div className='flex gap-2'><button onClick={()=>setShowCart(true)} className='border border-black rounded-full px-5 py-3 text-sm font-bold'>Ver mi pedido</button><button onClick={()=>setShowCart(true)} className='bg-green-500 text-black font-black px-6 py-3 rounded-full hidden md:block'>Ver carrito</button></div></div></div>{showCart&&(<div className='fixed inset-0 bg-black/60 z-50 flex items-end md:items-center justify-center p-0 md:p-6'><div className='bg-white w-full md:max-w-lg rounded-t-[24px] md:rounded-[24px] max-h-[85vh] flex flex-col overflow-hidden'><div className='p-5 border-b flex justify-between items-center'><h3 className='font-black text-lg'>Tu pedido ({totalItems}) - Antes de enviar</h3><button onClick={()=>setShowCart(false)} className='border rounded-full px-3 py-1 text-sm'>Cerrar</button></div><div className='flex-1 overflow-auto p-5 space-y-3'>{cart.map(c=>(<div key={c.id} className='flex gap-3 items-center border rounded-xl p-2'><img src={c.image_url} className='w-16 h-16 object-cover rounded-lg bg-gray-100'/><div className='flex-1'><p className='font-bold text-sm'>{c.name}</p><p className='text-xs text-gray-500'>C$ {c.price} x {c.qty} = C$ {c.price*c.qty}</p><div className='flex gap-2 mt-1 items-center'><button onClick={()=>updateQty(c.id,c.qty-1)} className='w-7 h-7 border rounded-full'>-</button><span className='text-sm font-bold'>{c.qty}</span><button onClick={()=>updateQty(c.id,c.qty+1)} className='w-7 h-7 border rounded-full'>+</button></div></div><button onClick={()=>removeFromCart(c.id)} className='text-xs text-red-500 border border-red-200 px-2 py-1 rounded-full'>Quitar</button></div>))}</div><div className='p-5 border-t bg-gray-50'><div className='flex justify-between font-black text-lg'><span>Total</span><span>C$ {total}</span></div><p className='text-[11px] text-gray-500 mt-1'>Revisa tu pedido antes de enviarlo por WhatsApp</p><button onClick={checkout} className='w-full mt-4 bg-green-500 text-black font-black py-4 rounded-full'>Enviar pedido por WhatsApp a {store.name}</button></div></div></div>)}</>)}</main>)
}
